version: "3.8"

services:
  catalogue:
    build:
      context: ./catalogue
      dockerfile: Dockerfile
    image: joindevops/catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb
    networks:
      - roboshop


  mongodb:
    build: ./mongodb
    image: joindevops/mongodb:v1
    container_name: mongodb
    volumes:
      - mongodb:/data/db
    networks:
      - roboshop

  redis:
    image: /redis:7.0
    container_name: redis
    volumes: 
      - redis:/data
    networks:
      - roboshop

  mysql:
    build: ./mysql
    image: joindevops/mysql:v1
    container_name: mysql
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - roboshop

  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop
    networks:
      - roboshop

  user:
    build: ./user
    image: joindevops/user:v1
    container_name: user
    depends_on:
      - mongodb
      - redis
    networks:
      - roboshop

  cart:
    build: ./cart
    image: joindevops/cart:v1
    container_name: cart
    depends_on:
      - redis
      - catalogue
    networks:
      - roboshop

  shipping:
    build: ./shipping
    image: joindevops/shipping:v1
    container_name: shipping
    depends_on:
      - mysql
      - cart
    networks:
      - roboshop

  payment:
    build: ./payment
    image: joindevops/payment:v1
    container_name: payment
    depends_on:
      - rabbitmq
      - cart
      - user
    networks:
      - roboshop

  frontend:
    build: ./frontend
    image: joindevops/frontend:v1
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - catalogue
      - user
      - cart
      - shipping
      - payment
    networks:
      - roboshop

networks:
  roboshop:
    name: roboshop
    external: false

volumes:
  mongodb:
  redis:
  mysql:
  rabbitmq:







  
















  










